# Generated by Django 6.0.6 on 2026-07-04 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("language", models.CharField(default="en", max_length=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("country", models.CharField(max_length=100)),
                ("tax_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "financial_year",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "company_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "business_experience",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("team_size", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "billing_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("purpose", models.CharField(blank=True, max_length=255, null=True)),
                ("onboarding_step", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
