# Generated by Django 6.0.6 on 2026-07-04 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_account", "0004_customer_chart_of_account_customer_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("gst_number", models.CharField(blank=True, max_length=100, null=True)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=100)),
                (
                    "order_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("footer", models.TextField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="bill_attachments/"
                    ),
                ),
                ("status", models.CharField(default="Draft", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="my_account.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="my_account.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="my_account.bill",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                fields=("company", "bill_number"), name="unique_bill_number_per_company"
            ),
        ),
    ]
