# Generated by Django 6.0.6 on 2026-07-04 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_account", "0006_vendor_address_finder_vendor_chart_of_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Bank", "Bank"), ("Credit Card", "Credit Card")],
                        default="Bank",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=100)),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("default_account", models.BooleanField(default=False)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                ("bank_phone", models.CharField(blank=True, max_length=50, null=True)),
                ("bank_address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="my_account.company",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "number"),
                        name="unique_account_number_per_company",
                    )
                ],
            },
        ),
    ]
