# Generated by Django 6.0.6 on 2026-07-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_account", "0011_report_scheduledreport_pinnedreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="basis",
            field=models.CharField(default="Accrual", max_length=100),
        ),
        migrations.AddField(
            model_name="report",
            name="group_by",
            field=models.CharField(default="None", max_length=100),
        ),
        migrations.AddField(
            model_name="report",
            name="period",
            field=models.CharField(default="Monthly", max_length=100),
        ),
    ]
