# Generated by Django 6.0.6 on 2026-07-04 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_account", "0012_report_basis_report_group_by_report_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo", models.CharField(default="bi-cpu", max_length=100)),
                ("banner_color", models.CharField(default="#565895", max_length=50)),
                ("category", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("developer", models.CharField(default="Akaunting", max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("status", models.CharField(default="Active", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AppInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed", models.BooleanField(default=False)),
                ("installed_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Installed", max_length=50)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_users",
                        to="my_account.app",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "app"), name="unique_user_app_installation"
                    )
                ],
            },
        ),
    ]
