# Generated by Django 6.0.6 on 2026-07-04 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_account", "0015_dashboard_dashboardwidget_dashboard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dashboardwidget",
            name="unique_user_widget_name",
        ),
        migrations.AddConstraint(
            model_name="dashboardwidget",
            constraint=models.UniqueConstraint(
                fields=("user", "dashboard", "widget_name"),
                name="unique_user_dashboard_widget_name",
            ),
        ),
    ]
