# Generated by Django 6.0.6 on 2026-07-04 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_account", "0016_remove_dashboardwidget_unique_user_widget_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                fields=("created_by", "name"), name="unique_created_by_dashboard_name"
            ),
        ),
    ]
