# Generated by Django 6.0.6 on 2026-07-10 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_account", "0019_estimate_estimateitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimates",
                to="my_account.invoice",
            ),
        ),
    ]
